project:
  type: website
  output-dir: docs
  
website:
  title: "GRUPO C"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: intro.qmd
        text: Informe
      - href: image_j.qmd
        text: ImageJ
      - href: Py.qmd
        text: Python
      - href: conda.qmd
        text: Anaconda
      - conclu.qmd
    tools:
      - icon: twitter
        href: https://twitter.com/
      - icon: github
        href: https://github.com/Gomezt13/unidad_iii.git
  page-footer:
    right: "Built with [Quarto](https://quarto.org/)"
    left: "&copy; Copyright 2024, Programación y Análisis de Datos"

format:
  html:
    theme: cerulean
    toc: true

editor: source

